[workspace]
resolver = "2"
members = [
    "examples/rust-wasm"
]

[workspace.dependencies]
wasm-bindgen = "0.2"
js-sys = "0.3"
wasm-bindgen-futures = "0.4"
console_error_panic_hook = "0.1"
web-sys = "0.3"

[profile.release]
opt-level = "s"
lto = true