[workspace]
resolver = "2"
members = ["examples/rust-wasm"]

[workspace.dependencies]
console_error_panic_hook = "0.1"
js-sys = "0.3"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = "0.3"

[profile.release]
opt-level = "s"
lto = true
