# Rust code formatting configuration - stable features only
edition = "2021"
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Default"
merge_derives = true
use_try_shorthand = false
use_field_init_shorthand = false